networks:
  back:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:17
    networks:
      - back
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      start_period: 1s
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - back
    env_file:
      - .env
    command: server ~/minio --console-address :9080
    ports:
      - '9080:9080'
      - '9000:9000'

  backend:
    container_name: spring
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    networks:
      - back
    ports:
      - 9090:9090
    working_dir: /boot
    env_file:
      .env
    environment:
      HOST: postgres:5432
      MINIO_HOST: minio:9000
    healthcheck:
      test: "wget --tries=1 -O- localhost:9090/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 120s