server:
  port: 9090
logging:
  level:
    ru.itmo.blpslab1: debug
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "blps-lab-1"
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  jwt:
    life-time: 3600000  # ms
    secret: ${SECRET}
minio:
  bucket: ${MINIO_BUCKET}
  url: http://${MINIO_HOST}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
